# settings
_min_copier_version: "9.3.0"
_templates_suffix: .jinja

# internal fields
_subdirectory: template

# Settings like `_skip_if_exists` are merged
_skip_if_exists:
  - LICENSE
  - CHANGELOG.md
  - CODE_OF_CONDUCT.md
  - .gitignore
  - .editorconfig
